services:
  reviews:
    build: .
    image: ghcr.io/nattrio/bookinfo-reviews:dev
    ports:
      - "8082:8082"
    environment:
      ENABLE_RATINGS: 'true'
      RATINGS_SERVICE: http://ratings:8080