reviews:
  namespace: student4-bookinfo-uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  image: ghcr.io/nattrio/bookinfo-reviews
  tag: uat
ingress:
  host: sitkmutt.bookinfo.uat.opsta.net
  path: "/student4/reviews(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2